/**
 * Created by chenjianjun on 16/3/16.
 */
import { BaseConfig } from './base'
import _ from 'lodash'

const ActiveConfig = {
  // 关于我们
  'aboutUs': {
    kClass:'layout-center-box',
    pic:[
      {
        'url':'//img2.jsbn.com/static/about_us/01.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/about_us/02.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/about_us/03.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/about_us/04.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/about_us/05.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/about_us/06.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/about_us/07.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/about_us/08.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/about_us/09.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/about_us/10.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/about_us/11.jpg',
        'href':false,
        'hrefUrl':''
      }
    ]
  },
  '3yhq':{
    kClass:'topic',
    pic:[
      {
        'url':'//img2.jsbn.com/static/activities/3mhq/langman_01.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/activities/3mhq/langman_02.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/activities/3mhq/langman_03.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/activities/3mhq/langman_04.jpg',
        'href':true,
        'hrefUrl':'/suite'
      },
      {
        'url':'//img2.jsbn.com/static/activities/3mhq/langman_05.jpg',
        'href':true,
        'hrefUrl':'/suite'
      },
      {
        'url':'//img2.jsbn.com/static/activities/3mhq/langman_06.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/activities/3mhq/langman_07.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/activities/3mhq/langman_08.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/activities/3mhq/langman_09.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/activities/3mhq/langman_10.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/activities/3mhq/langman_11.jpg',
        'href':true,
        'hrefUrl':'//chat16.live800.com/live800/chatClient/chatbox.jsp?companyID=533854&configID=75804&jid=6937519900&skillId=4927'
      },
      {
        'url':'//img2.jsbn.com/static/activities/3mhq/langman_12.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/activities/3mhq/langman_13.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/activities/3mhq/langman_14.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/activities/3mhq/langman_15.jpg',
        'href':true,
        'hrefUrl':'//chat16.live800.com/live800/chatClient/chatbox.jsp?companyID=533854&configID=75804&jid=6937519900&skillId=4927'
      },
      {
        'url':'//img2.jsbn.com/static/activities/3mhq/langman_16.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/activities/3mhq/langman_17.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/activities/3mhq/langman_18.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/activities/3mhq/langman_19.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/activities/3mhq/langman_20.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/activities/3mhq/langman_21.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/activities/3mhq/langman_22.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/activities/3mhq/langman_23.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/activities/3mhq/langman_24.jpg',
        'href':false,
        'hrefUrl':''
      },
      {
        'url':'//img2.jsbn.com/static/activities/3mhq/langman_25.jpg',
        'href':false,
        'hrefUrl':''
      }
    ]
  }
}

export { ActiveConfig }
